### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by irenge** [SoveraNia/SyzVegas#2]
Hi I go that issue when I run make in the syz-Vegas folder

tools/syz-env/env.go:52:36: target.CrossCFlags undefined (type *targets.Target has no field or method CrossCFlags)
Makefile:35: *** syz-env failed. Stop.

Am I missing something

host OS : Ubuntu 18.04.06 LTS
go version go1.11.13

**Comment by irenge** [comment]
I solved that by matching version

**Comment by De4dCr0w** [comment]
Hi, I have the same problem, what version are you using to solve?
